import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Cabecalho from '../../Components/cabecalho/cabecalho'
import Rodape from '../../Components/Rodape/rodape/Rodape'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'entrega 4',
  description: 'Generated by 1TDSPV',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
        <Cabecalho/>
        </div>
        {children}
        <Rodape/>        
        </body>
    </html>
  )
}
